# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49a22ba4f168e46473e1b3abe0c75eaf753b3be06f8775968ac5e2b4e925bd331b6413047dd31644ea1c869d8ba5f4793a682704ce35df8b6746164e33a8edd5

test:
  secret_key_base: 66c32e9cdff2e1a52ea8127b770ffb394236fa0ef161fe9d5e7cfdc6254c8998b9143b4267e92e81061843dd4f89a83522f73ab9648e2331dcddcf6ccb741173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
